### PR TITLE
escape {} into '' for non-standard filenames

### PR DESCRIPTION
**Pull request by adamant-pwn**

### CODE REVIEW

**Comment by akahles** [comment]
Is there a test case for this?

**Comment by adamant-pwn** [comment]
It got triggered on the file `MLHC_lecture/project3/student_submissions/project3/cracra2019/MITBIH dataset/MITBIH - Models (1).ipynb`, because it contains unescaped `(1)` in the filename. I didn't look into how tests are done in this particular project, but I suppose there isn't, since it failed :thinking:

**Comment by akahles** [comment]
The tests are run as part of the CI using pytest. Would you mind having a look? If I remember correctly, there is some code generating some unicode filenames, testing some corner cases. Maybe this could be extended.

**Comment by adamant-pwn** [comment]
I've updated the testcase to cover this, and also checked that [it would fail without this change](https://github.com/ratschlab/tools-project-archives/actions/runs/11902164041).

**Comment by akahles** [comment]
Thanks - LGTM

**Pull request merged**
