### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by adamant-pwn**
It seems the project is not uploaded to PyPI and should be installed manually

### CODE REVIEW

**Comment by adamant-pwn** [comment]
Actually it seems that PyPI deployment was added in #36, so I'm not sure I fully understand why the package is not there.

**Comment by akahles** [comment]
Package is now on PyPI. Maybe we no longer need this?

**Comment by adamant-pwn** [comment]
Returned PyPI mention and amended this into just adding a separate section. I think it's still useful, as the later method makes it easier to quickly fix something in the archiver locally if it suddenly throws an error. I think it's still be better to add.

**Comment by akahles** [comment]
Thanks - Looks good

**Pull request merged**
